import { Car } from '../types';
import { generateSearchLinks } from '../../lib/generateSearchLinks';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    title: 'BMW Serie 3 320d xDrive Touring',
    brand: 'BMW',
    model: 'Serie 3',
    year: 2020,
    price: 24900,
    km: 58000,
    fuel: 'diesel',
    bodyType: 'familiar',
    province: 'Madrid',
    seller: 'profesional',
    platform: 'coches.net',
    url: 'https://www.coches.net',
    image: getCarImage('BMW', 'Serie 3'),
    createdAt: '2024-03-15T10:00:00Z',
  },

  {
    id: '2',
    title: 'Audi Q3 2.0 TDI',
    brand: 'Audi',
    model: 'Q3',
    year: 2021,
    price: 27900,
    km: 43000,
    fuel: 'diesel',
    bodyType: 'suv',
    province: 'Barcelona',
    seller: 'profesional',
    platform: 'autoscout24',
    url: 'https://www.autoscout24.es',
    image: getCarImage('Audi', 'Q3'),
    createdAt: '2024-03-14T10:00:00Z',
  },

  {
    id: '3',
    title: 'Mercedes-Benz GLA 200d',
    brand: 'Mercedes-Benz',
    model: 'GLA',
    year: 2021,
    price: 33900,
    km: 32000,
    fuel: 'diesel',
    bodyType: 'suv',
    province: 'Valencia',
    seller: 'profesional',
    platform: 'milanuncios',
    url: 'https://www.milanuncios.com',
    image: getCarImage('Mercedes-Benz', 'GLA'),
    createdAt: '2024-03-13T10:00:00Z',
  },

  {
    id: '4',
    title: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    price: 36900,
    km: 28000,
    fuel: 'electrico',
    bodyType: 'berlina',
    province: 'Madrid',
    seller: 'particular',
    platform: 'wallapop',
    url: 'https://es.wallapop.com',
    image: getCarImage('Tesla', 'Model 3'),
    createdAt: '2024-03-12T10:00:00Z',
  },
];
