import { Car } from '../types';
import { getCarImage } from '../lib/getCarImage';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    title: 'BMW Serie 3 320d xDrive Touring',
    brand: 'BMW',
    model: 'Serie 3',
    year: 2020,
    price: 24900,
    km: 58000,
    fuel: 'diesel',
    bodyType: 'familiar',
    province: 'Madrid',
    seller: 'profesional',
    platform: 'coches.net',
    url: 'https://www.coches.net',
    image: getCarImage('BMW', 'Serie 3'),
    color: 'Negro',
    transmission: 'Automático',
    power: 190,
    doors: 5,
    description: 'BMW Serie 3 Touring en excelente estado.',
    createdAt: '2024-03-15T10:00:00Z',
  },

  {
    id: '2',
    title: 'Audi Q3 2.0 TDI 150cv S tronic',
    brand: 'Audi',
    model: 'Q3',
    year: 2021,
    price: 27900,
    km: 43000,
    fuel: 'diesel',
    bodyType: 'suv',
    province: 'Barcelona',
    seller: 'profesional',
    platform: 'autoscout24',
    url: 'https://www.autoscout24.es',
    image: getCarImage('Audi', 'Q3'),
    color: 'Blanco',
    transmission: 'Automático',
    power: 150,
    doors: 5,
    description: 'Audi Q3 con Virtual Cockpit y Matrix LED.',
    createdAt: '2024-03-14T10:00:00Z',
  },

  {
    id: '3',
    title: 'Mercedes-Benz GLA 200d AMG Line',
    brand: 'Mercedes-Benz',
    model: 'GLA',
    year: 2021,
    price: 33900,
    km: 32000,
    fuel: 'diesel',
    bodyType: 'suv',
    province: 'Valencia',
    seller: 'profesional',
    platform: 'milanuncios',
    url: 'https://www.milanuncios.com',
    image: getCarImage('Mercedes-Benz', 'GLA'),
    color: 'Gris',
    transmission: 'Automático',
    power: 150,
    doors: 5,
    description: 'Mercedes GLA AMG Line con techo panorámico.',
    createdAt: '2024-03-13T10:00:00Z',
  },

  {
    id: '4',
    title: 'Tesla Model 3 Long Range AWD',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    price: 36900,
    km: 28000,
    fuel: 'electrico',
    bodyType: 'berlina',
    province: 'Madrid',
    seller: 'particular',
    platform: 'wallapop',
    url: 'https://es.wallapop.com',
    image: getCarImage('Tesla', 'Model 3'),
    color: 'Blanco',
    transmission: 'Automático',
    power: 450,
    doors: 4,
    description: 'Tesla Model 3 Long Range con Autopilot.',
    createdAt: '2024-03-12T10:00:00Z',
  },

  {
    id: '5',
    title: 'Toyota RAV4 Hybrid Executive',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2021,
    price: 31400,
    km: 39000,
    fuel: 'hibrido',
    bodyType: 'suv',
    province: 'Sevilla',
    seller: 'profesional',
    platform: 'coches.net',
    url: 'https://www.coches.net',
    image: getCarImage('Toyota', 'RAV4'),
    color: 'Azul',
    transmission: 'Automático',
    power: 222,
    doors: 5,
    description: 'Toyota RAV4 Hybrid con garantía oficial.',
    createdAt: '2024-03-11T10:00:00Z',
  },

  {
    id: '6',
    title: 'Volkswagen Golf 2.0 TDI DSG',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2020,
    price: 18900,
    km: 61000,
    fuel: 'diesel',
    bodyType: 'compacto',
    province: 'Bilbao',
    seller: 'profesional',
    platform: 'autoscout24',
    url: 'https://www.autoscout24.es',
    image: getCarImage('Volkswagen', 'Golf'),
    color: 'Gris',
    transmission: 'Automático',
    power: 150,
    doors: 5,
    description: 'Volkswagen Golf Advance muy equipado.',
    createdAt: '2024-03-10T10:00:00Z',
  },
];
